### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by johnvanbreda** [litespeedtech/lscache-drupal#27]
I upgraded my v1.0 lscache Drupal module to v1.2 by putting the site in maintenance mode, then copying the files over. After doing this, my site was broken. I recovered by replacing the module files, then found this in the Drupal log:
```
Error: Class 'Drupal\lite_speed_cache\StackMiddleware\LiteSpeedCache' not found in Drupal\Component\DependencyInjection\Container->createService() (line 262 of /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php)
#0 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'http_middleware...')
#1 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(437): Drupal\Component\DependencyInjection\Container->get('http_middleware...', 1)
#2 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(240): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#3 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'http_middleware...')
#4 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(437): Drupal\Component\DependencyInjection\Container->get('http_middleware...', 1)
#5 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(240): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#6 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'http_middleware...')
#7 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(437): Drupal\Component\DependencyInjection\Container->get('http_middleware...', 1)
#8 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(240): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#9 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'http_middleware...')
#10 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(437): Drupal\Component\DependencyInjection\Container->get('http_middleware...', 1)
#11 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(240): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#12 /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'http_kernel')
#13 /home/nature50/public_html/core/lib/Drupal/Core/DrupalKernel.php(1370): Drupal\Component\DependencyInjection\Container->get('http_kernel')
#14 /home/nature50/public_html/core/lib/Drupal/Core/DrupalKernel.php(717): Drupal\Core\DrupalKernel->getHttpKernel()
#15 /home/nature50/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
```

I managed to do the upgrade by uninstalling the old module, replacing it, then re-installing it.

**Comment by wadedang** [comment]
Hello
Could you share the 

- /home/nature50/public_html/modules/lscache-drupal-master/src/StackMiddleware/LiteSpeedCache.php

- /home/nature50/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php

with me?

**Comment by johnvanbreda** [comment]
Sure - in the attached zip file.
[files.zip](https://github.com/litespeedtech/lscache-drupal/files/9315153/files.zip)
